import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import type { QuizRecommendation } from "@/types/quiz";

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: "Helvetica",
    backgroundColor: "#FBF9F4",
  },
  eyebrow: {
    fontSize: 10,
    color: "#B85C3E",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    color: "#20241F",
    marginBottom: 20,
    fontFamily: "Helvetica-Bold",
  },
  paragraph: {
    fontSize: 12,
    color: "#20241F",
    lineHeight: 1.6,
    marginBottom: 20,
  },
  footer: {
    fontSize: 10,
    color: "#5C8A56",
    marginTop: 40,
  },
});

export function QuizResultPDF({ recommendation }: { recommendation: QuizRecommendation }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.eyebrow}>Your Recommended Field — Aletheia</Text>
        <Text style={styles.title}>{recommendation.recommendedField}</Text>
        <Text style={styles.paragraph}>{recommendation.reasoning}</Text>
        <Text style={styles.footer}>
          Generated by Aletheia — a guide for computer science students.
        </Text>
      </Page>
    </Document>
  );
}